name: PlaxerHub
version: '${project.version}'
main: org.plaxerstudios.it.plaxerhub.PlaxerHub
api-version: 1.18
authors: [Plaxer's Studios developer]
commands:
  hub:
  sethub:
    permission: plaxerhub.sethub
